export const interviewersData = [
  {
    id: 1,
    name: "Amit Sharma",
    email: "amit.sharma@example.com",
    totalSlots: 10,
    bookedSlots: 3,
    availableSlots: 7,
    meetings: [
      {
        intervieweeName: "Riya Verma",
        intervieweeEmail: "riya.verma@example.com",
        date: "2025-07-24",
        time: "10:00 AM",
        meetingLink: "https://meet.example.com/amit-riya",
      },
      {
        intervieweeName: "Kunal Singh",
        intervieweeEmail: "kunal.singh@example.com",
        date: "2025-07-24",
        time: "11:00 AM",
        meetingLink: "https://meet.example.com/amit-kunal",
      },
      {
        intervieweeName: "Neha Patil",
        intervieweeEmail: "neha.patil@example.com",
        date: "2025-07-25",
        time: "09:30 AM",
        meetingLink: "https://meet.example.com/amit-neha",
      },
    ],
  },
  {
    id: 2,
    name: "Priya Nair",
    email: "priya.nair@example.com",
    totalSlots: 8,
    bookedSlots: 2,
    availableSlots: 6,
    meetings: [
      {
        intervieweeName: "Manish Gupta",
        intervieweeEmail: "manish.gupta@example.com",
        date: "2025-07-24",
        time: "09:00 AM",
        meetingLink: "https://meet.example.com/priya-manish",
      },
      {
        intervieweeName: "Shruti Rao",
        intervieweeEmail: "shruti.rao@example.com",
        date: "2025-07-24",
        time: "10:00 AM",
        meetingLink: "https://meet.example.com/priya-shruti",
      },
    ],
  },
  {
    id: 3,
    name: "Rajeev Ranjan",
    email: "rajeev.ranjan@example.com",
    totalSlots: 6,
    bookedSlots: 1,
    availableSlots: 5,
    meetings: [
      {
        intervieweeName: "Aisha Khan",
        intervieweeEmail: "aisha.khan@example.com",
        date: "2025-07-25",
        time: "11:30 AM",
        meetingLink: "https://meet.example.com/rajeev-aisha",
      },
    ],
  },
  {
    id: 4,
    name: "Sonal Desai",
    email: "sonal.desai@example.com",
    totalSlots: 9,
    bookedSlots: 0,
    availableSlots: 9,
    meetings: [],
  },
  {
    id: 5,
    name: "Karthik Iyer",
    email: "karthik.iyer@example.com",
    totalSlots: 7,
    bookedSlots: 4,
    availableSlots: 3,
    meetings: [
      {
        intervieweeName: "Tanya Shah",
        intervieweeEmail: "tanya.shah@example.com",
        date: "2025-07-23",
        time: "03:00 PM",
        meetingLink: "https://meet.example.com/karthik-tanya",
      },
      {
        intervieweeName: "Raghav Kapoor",
        intervieweeEmail: "raghav.kapoor@example.com",
        date: "2025-07-23",
        time: "04:00 PM",
        meetingLink: "https://meet.example.com/karthik-raghav",
      },
      {
        intervieweeName: "Esha Bansal",
        intervieweeEmail: "esha.bansal@example.com",
        date: "2025-07-24",
        time: "12:00 PM",
        meetingLink: "https://meet.example.com/karthik-esha",
      },
      {
        intervieweeName: "Nikhil Rao",
        intervieweeEmail: "nikhil.rao@example.com",
        date: "2025-07-24",
        time: "01:00 PM",
        meetingLink: "https://meet.example.com/karthik-nikhil",
      },
    ],
  },
  {
    id: 6,
    name: "Meera Joshi",
    email: "meera.joshi@example.com",
    totalSlots: 5,
    bookedSlots: 2,
    availableSlots: 3,
    meetings: [
      {
        intervieweeName: "Kabir Sinha",
        intervieweeEmail: "kabir.sinha@example.com",
        date: "2025-07-22",
        time: "02:00 PM",
        meetingLink: "https://meet.example.com/meera-kabir",
      },
      {
        intervieweeName: "Ira Dubey",
        intervieweeEmail: "ira.dubey@example.com",
        date: "2025-07-22",
        time: "03:00 PM",
        meetingLink: "https://meet.example.com/meera-ira",
      },
    ],
  },
  {
    id: 7,
    name: "Naveen Menon",
    email: "naveen.menon@example.com",
    totalSlots: 10,
    bookedSlots: 0,
    availableSlots: 10,
    meetings: [],
  },
  {
    id: 8,
    name: "Swati Agarwal",
    email: "swati.agarwal@example.com",
    totalSlots: 6,
    bookedSlots: 3,
    availableSlots: 3,
    meetings: [
      {
        intervieweeName: "Divya Nair",
        intervieweeEmail: "divya.nair@example.com",
        date: "2025-07-26",
        time: "10:00 AM",
        meetingLink: "https://meet.example.com/swati-divya",
      },
      {
        intervieweeName: "Zaid Khan",
        intervieweeEmail: "zaid.khan@example.com",
        date: "2025-07-26",
        time: "11:00 AM",
        meetingLink: "https://meet.example.com/swati-zaid",
      },
      {
        intervieweeName: "Sneha Yadav",
        intervieweeEmail: "sneha.yadav@example.com",
        date: "2025-07-26",
        time: "12:00 PM",
        meetingLink: "https://meet.example.com/swati-sneha",
      },
    ],
  },
  {
    id: 9,
    name: "Ankit Verma",
    email: "ankit.verma@example.com",
    totalSlots: 4,
    bookedSlots: 1,
    availableSlots: 3,
    meetings: [
      {
        intervieweeName: "Harshit Kaul",
        intervieweeEmail: "harshit.kaul@example.com",
        date: "2025-07-27",
        time: "09:00 AM",
        meetingLink: "https://meet.example.com/ankit-harshit",
      },
    ],
  },
  {
    id: 10,
    name: "Lavanya Reddy",
    email: "lavanya.reddy@example.com",
    totalSlots: 7,
    bookedSlots: 4,
    availableSlots: 3,
    meetings: [
      {
        intervieweeName: "Aditya Rao",
        intervieweeEmail: "aditya.rao@example.com",
        date: "2025-07-25",
        time: "02:00 PM",
        meetingLink: "https://meet.example.com/lavanya-aditya",
      },
      {
        intervieweeName: "Naina Kapoor",
        intervieweeEmail: "naina.kapoor@example.com",
        date: "2025-07-25",
        time: "03:00 PM",
        meetingLink: "https://meet.example.com/lavanya-naina",
      },
      {
        intervieweeName: "Samar Taneja",
        intervieweeEmail: "samar.taneja@example.com",
        date: "2025-07-26",
        time: "11:30 AM",
        meetingLink: "https://meet.example.com/lavanya-samar",
      },
      {
        intervieweeName: "Nidhi Saxena",
        intervieweeEmail: "nidhi.saxena@example.com",
        date: "2025-07-26",
        time: "12:30 PM",
        meetingLink: "https://meet.example.com/lavanya-nidhi",
      },
    ],
  },
];
