export const intervieweesData = [
  {
    name: "Riya Verma",
    email: "riya.verma@example.com",
    phone: "+91-9876543210",
    slotBooked: true,
    details: {
      interviewerName: "Amit Sharma",
      date: "2025-07-24",
      time: "10:00 AM",
      meetingLink: "https://meet.example.com/amit-riya",
    },
  },
  {
    name: "Sneha Yadav",
    email: "sneha.yadav@example.com",
    phone: "+91-9800765432",
    slotBooked: false,
  },
  {
    name: "Kunal Singh",
    email: "kunal.singh@example.com",
    phone: "+91-9876501234",
    slotBooked: true,
    details: {
      interviewerName: "Amit Sharma",
      date: "2025-07-24",
      time: "11:00 AM",
      meetingLink: "https://meet.example.com/amit-kunal",
    },
  },
  {
    name: "Neha Patil",
    email: "neha.patil@example.com",
    phone: "+91-9845012345",
    slotBooked: true,
    details: {
      interviewerName: "Amit Sharma",
      date: "2025-07-25",
      time: "09:30 AM",
      meetingLink: "https://meet.example.com/amit-neha",
    },
  },
  {
    name: "Manish Gupta",
    email: "manish.gupta@example.com",
    phone: "+91-9888997766",
    slotBooked: true,
    details: {
      interviewerName: "Priya Nair",
      date: "2025-07-24",
      time: "09:00 AM",
      meetingLink: "https://meet.example.com/priya-manish",
    },
  },
  {
    name: "Shruti Rao",
    email: "shruti.rao@example.com",
    phone: "+91-9811122233",
    slotBooked: true,
    details: {
      interviewerName: "Priya Nair",
      date: "2025-07-24",
      time: "10:00 AM",
      meetingLink: "https://meet.example.com/priya-shruti",
    },
  },
  {
    name: "Tanya Shah",
    email: "tanya.shah@example.com",
    phone: "+91-9898989898",
    slotBooked: true,
    details: {
      interviewerName: "Karthik Iyer",
      date: "2025-07-23",
      time: "03:00 PM",
      meetingLink: "https://meet.example.com/karthik-tanya",
    },
  },
  {
    name: "Nikhil Rao",
    email: "nikhil.rao@example.com",
    phone: "+91-9877001122",
    slotBooked: true,
    details: {
      interviewerName: "Karthik Iyer",
      date: "2025-07-24",
      time: "01:00 PM",
      meetingLink: "https://meet.example.com/karthik-nikhil",
    },
  },
  {
    name: "Aisha Khan",
    email: "aisha.khan@example.com",
    phone: "+91-9833445566",
    slotBooked: true,
    details: {
      interviewerName: "Rajeev Ranjan",
      date: "2025-07-25",
      time: "11:30 AM",
      meetingLink: "https://meet.example.com/rajeev-aisha",
    },
  },
  {
    name: "Kabir Sinha",
    email: "kabir.sinha@example.com",
    phone: "+91-9812345678",
    slotBooked: false,
  },
];
