// export const meetings = [
//   {
//     id: 1,
//     interviewer_name: "Sarah Johnson",
//     interviewer_email: "sarah.johnson@techcorp.com",
//     interviewer_phone: "+1-555-0123",
//     scheduled_time: "10:00 AM",
//     scheduled_date: "2025-07-15",
//   },
//   {
//     id: 2,
//     interviewer_name: "Michael Chen",
//     interviewer_email: "m.chen@innovate.io",
//     interviewer_phone: "+1-555-0124",
//     scheduled_time: "2:30 PM",
//     scheduled_date: "2025-07-22",
//   },
//   {
//     id: 3,
//     interviewer_name: "Emily Rodriguez",
//     interviewer_email: "emily.r@startupx.com",
//     interviewer_phone: "+1-555-0125",
//     scheduled_time: "11:15 AM",
//     scheduled_date: "2025-07-28",
//   },
//   {
//     id: 4,
//     interviewer_name: "David Kim",
//     interviewer_email: "david.kim@globaltech.net",
//     interviewer_phone: "+1-555-0126",
//     scheduled_time: "9:00 AM",
//     scheduled_date: "2025-07-18",
//   },
//   {
//     id: 5,
//     interviewer_name: "Lisa Thompson",
//     interviewer_email: "lisa.t@financeplus.com",
//     interviewer_phone: "+1-555-0127",
//     scheduled_time: "3:45 PM",
//     scheduled_date: "2025-08-05",
//   },
//   {
//     id: 6,
//     interviewer_name: "Robert Martinez",
//     interviewer_email: "r.martinez@consultgroup.org",
//     interviewer_phone: "+1-555-0128",
//     scheduled_time: "1:00 PM",
//     scheduled_date: "2025-07-10",
//   },
//   {
//     id: 7,
//     interviewer_name: "Jennifer Lee",
//     interviewer_email: "jennifer.lee@healthsys.com",
//     interviewer_phone: "+1-555-0129",
//     scheduled_time: "4:20 PM",
//     scheduled_date: "2025-07-22",
//   },
//   {
//     id: 8,
//     interviewer_name: "Mark Wilson",
//     interviewer_email: "mark.wilson@edtech.edu",
//     interviewer_phone: "+1-555-0130",
//     scheduled_time: "8:30 AM",
//     scheduled_date: "2025-08-12",
//   },
//   {
//     id: 9,
//     interviewer_name: "Amanda Garcia",
//     interviewer_email: "a.garcia@retailworks.com",
//     interviewer_phone: "+1-555-0131",
//     scheduled_time: "12:15 PM",
//     scheduled_date: "2025-07-08",
//   },
//   {
//     id: 10,
//     interviewer_name: "James Brown",
//     interviewer_email: "james.brown@manufacturing.inc",
//     interviewer_phone: "+1-555-0132",
//     scheduled_time: "10:45 AM",
//     scheduled_date: "2025-07-30",
//   },
//   {
//     id: 11,
//     interviewer_name: "Rachel Davis",
//     interviewer_email: "rachel.d@mediaco.com",
//     interviewer_phone: "+1-555-0133",
//     scheduled_time: "2:00 PM",
//     scheduled_date: "2025-07-12",
//   },
//   {
//     id: 12,
//     interviewer_name: "Kevin O'Connor",
//     interviewer_email: "kevin.oconnor@lawfirm.legal",
//     interviewer_phone: "+1-555-0134",
//     scheduled_time: "9:30 AM",
//     scheduled_date: "2025-08-18",
//   },
//   {
//     id: 13,
//     interviewer_name: "Stephanie Wang",
//     interviewer_email: "s.wang@biotech.research",
//     interviewer_phone: "+1-555-0135",
//     scheduled_time: "11:00 AM",
//     scheduled_date: "2025-07-22",
//   },
//   {
//     id: 14,
//     interviewer_name: "Carlos Mendez",
//     interviewer_email: "carlos.mendez@construction.build",
//     interviewer_phone: "+1-555-0136",
//     scheduled_time: "3:15 PM",
//     scheduled_date: "2025-07-05",
//   },
//   {
//     id: 15,
//     interviewer_name: "Nicole Foster",
//     interviewer_email: "n.foster@hospitalgroup.med",
//     interviewer_phone: "+1-555-0137",
//     scheduled_time: "1:30 PM",
//     scheduled_date: "2025-08-22",
//   },
//   {
//     id: 16,
//     interviewer_name: "Andrew Taylor",
//     interviewer_email: "andrew.taylor@aerospace.fly",
//     interviewer_phone: "+1-555-0138",
//     scheduled_time: "8:00 AM",
//     scheduled_date: "2025-07-16",
//   },
//   {
//     id: 17,
//     interviewer_name: "Christina Park",
//     interviewer_email: "christina.p@fashionhouse.style",
//     interviewer_phone: "+1-555-0139",
//     scheduled_time: "4:00 PM",
//     scheduled_date: "2025-09-02",
//   },
//   {
//     id: 18,
//     interviewer_name: "Daniel Scott",
//     interviewer_email: "daniel.scott@energy.power",
//     interviewer_phone: "+1-555-0140",
//     scheduled_time: "10:20 AM",
//     scheduled_date: "2025-07-03",
//   },
//   {
//     id: 19,
//     interviewer_name: "Maria Gonzalez",
//     interviewer_email: "maria.gonzalez@foodcorp.eat",
//     interviewer_phone: "+1-555-0141",
//     scheduled_time: "2:45 PM",
//     scheduled_date: "2025-07-25",
//   },
//   {
//     id: 20,
//     interviewer_name: "Thomas Anderson",
//     interviewer_email: "t.anderson@insurance.protect",
//     interviewer_phone: "+1-555-0142",
//     scheduled_time: "9:15 AM",
//     scheduled_date: "2025-08-08",
//   },
//   {
//     id: 21,
//     interviewer_name: "Laura Mitchell",
//     interviewer_email: "laura.mitchell@realestate.homes",
//     interviewer_phone: "+1-555-0143",
//     scheduled_time: "11:30 AM",
//     scheduled_date: "2025-07-20",
//   },
//   {
//     id: 22,
//     interviewer_name: "Brian Clark",
//     interviewer_email: "brian.clark@logistics.move",
//     interviewer_phone: "+1-555-0144",
//     scheduled_time: "1:45 PM",
//     scheduled_date: "2025-09-10",
//   },
//   {
//     id: 23,
//     interviewer_name: "Michelle Wright",
//     interviewer_email: "m.wright@nonprofit.org",
//     interviewer_phone: "+1-555-0145",
//     scheduled_time: "3:00 PM",
//     scheduled_date: "2025-07-01",
//   },
//   {
//     id: 24,
//     interviewer_name: "Ryan Murphy",
//     interviewer_email: "ryan.murphy@gaming.play",
//     interviewer_phone: "+1-555-0146",
//     scheduled_time: "10:00 AM",
//     scheduled_date: "2025-08-15",
//   },
//   {
//     id: 25,
//     interviewer_name: "Samantha Hill",
//     interviewer_email: "samantha.hill@consulting.advise",
//     interviewer_phone: "+1-555-0147",
//     scheduled_time: "12:30 PM",
//     scheduled_date: "2025-07-22",
//   },
//   {
//     id: 26,
//     interviewer_name: "Gregory Adams",
//     interviewer_email: "greg.adams@automotive.drive",
//     interviewer_phone: "+1-555-0148",
//     scheduled_time: "8:45 AM",
//     scheduled_date: "2025-07-14",
//   },
//   {
//     id: 27,
//     interviewer_name: "Diana Cooper",
//     interviewer_email: "diana.cooper@pharma.heal",
//     interviewer_phone: "+1-555-0149",
//     scheduled_time: "4:15 PM",
//     scheduled_date: "2025-08-28",
//   },
//   {
//     id: 28,
//     interviewer_name: "Jonathan Reed",
//     interviewer_email: "j.reed@banking.money",
//     interviewer_phone: "+1-555-0150",
//     scheduled_time: "9:45 AM",
//     scheduled_date: "2025-07-07",
//   },
//   {
//     id: 29,
//     interviewer_name: "Vanessa Bell",
//     interviewer_email: "vanessa.bell@travel.explore",
//     interviewer_phone: "+1-555-0151",
//     scheduled_time: "2:20 PM",
//     scheduled_date: "2025-09-05",
//   },
//   {
//     id: 30,
//     interviewer_name: "Patrick Hughes",
//     interviewer_email: "patrick.hughes@security.safe",
//     interviewer_phone: "+1-555-0152",
//     scheduled_time: "11:45 AM",
//     scheduled_date: "2025-07-11",
//   },
// ];

export const meetings = [];
